baseURL: "https://www.fh-bielefeld.de/elearning/data/FH-Bielefeld/lm_data/lm_1359639/"
canonifyURLs: true   # prepend all relative URLs w/ baseURL
relativeURLs: false  # do NOT rewrite relative URLs to be relative to current content
uglyurls: true       # use foo.de/bar.html instead of foo.de/bar/ (our new ILIAS 7.x HTML-Lernmodul won't find landing pages else)

languageCode: "de-DE"
metaDataFormat: "yaml"
theme:
  - "hugo-lecture"
  - "hugo-theme-relearn"

themesDir: ".hugo"
contentDir: "temp/content"
publishDir: "docs"

params:
  editURL: "https://github.com/Programmiermethoden/PM-Lecture/edit/master/markdown/"
  author: "cagix"
  themeVariant: "green"
  titleSeparator: " "
  showVisitedLinks: true
  disableBreadcrumb: true
  disableInlineCopyToClipBoard: true
  disableNextPrev: true
  disableSearch: true
  disableLandingPageButton: true
  disableMathJax: false
  disableMermaid: true
  themeVariant:
  - "relearn-light"
  - "relearn-dark"
  - "green"

menu:
  shortcuts:
  - name: "<i class='fas fa-bookmark'></i> Fahrplan"
    url: "/org/schedule.html"
    weight: 10
  - name: "<i class='fas fa-bookmark'></i> Praktikum"
    url: "/assignments.html"
    weight: 10
  - name: "<i class='fas fa-bookmark'></i> Note/Credits"
    url: "/org/grading.html"
    weight: 20
  - name: "<i class='fas fa-bookmark'></i> Syllabus"
    url: "/org/syllabus.html"
    weight: 30
  - name: "<i class='fas fa-bookmark'></i> Ressourcen"
    url: "/org/resources.html"
    weight: 40
  - name: "<i class='fas fa-bookmark'></i> Prüfungsvorbereitung"
    url: "/org/exam.html"
    weight: 50

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
    privacyEnhanced: true
