name: demo
on:
    push:
        branches: [master]
    workflow_dispatch:


jobs:
    job1:
        runs-on: ubuntu-latest
        container:
            image: docker://openjdk:17
            volumes:
                - "$PWD":/data
        steps:
            - run: echo "Java Version:"
            - run: java -version
            - run: javac Hello.java
            - run: java Hello
            - run: ls -lags
