name: Check Markdown Links
on:
  # manually triggered
  workflow_dispatch:


jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: 'mlc_config.json'
          folder-path: 'markdown/'
          file-path: 'README.md, pm.bib'

